# Вебинары курса Рекомендательные системы

# Вебинар 1. Введение, примеры задач, бизнес- и ML-метрики

-----

# 1. Введение и примеры задач

RecSys everywhere

##  Постановка задачи

*Задача рекомендаций* - предложить пользователю товары, которые ему "понравятся"

Компоненты:
    - Пользователи (users)
    - Товары (items)
    - Взаимодействия (interactions) - по ним понимаем, что товар "понравился"

---

## Пользователи VS Товары

**Кейс**: определить в каждой ситуации, что является пользователем, а что - товаром
    
    1. На сайте Кинопоиска порекомендовать интересные фильмы
    2. На сайте hh.ru подобрать лучшие вакансии для соискателя вакансий
    3. На сайте hh.ru найти похожие вакансии на ту, которую сейчас просматривает пользователь ("вам также может понравиться")
    3. На сайте hh.ru подобрать лучших кандидатов для работодателя
    
*Пример ответа в чате:*
    1. Пользователь (П) - фильм, Товар (T) - фильм
    2. П - работодатель, Т - соискатель вакансий

Ответ:
1) Пользователь - пользователь, товар - фильм
2) Пользователь - соискатель, товар - вакансия
3) Пользователь - соискатель, товар - вакансия
4) Пользователь - работодатель, товар - соискатель (кандидат)

---

## Взаимодействия --> "понравился товар"

---

## В чем отличие от классификации?

In [76]:
import pandas as pd
import numpy as np

In [77]:
pd.DataFrame([['Иван', 'Хлеб Бородинский', 1],
             ['Иван', 'Хлеб Белый', 0],
             ['Василий', 'Йогурт Epica', 1]], columns=['user', 'item', 'purchase_fact'])

      user              item  purchase_fact
0     Иван  Хлеб Бородинский              1
1     Иван        Хлеб Белый              0
2  Василий      Йогурт Epica              1

Ведь можно добавить фичи на user (средний чек, кол-во покупок в категориях и т.д),
на item (цена, кол-во продаж в неделю и т.l), и решать задачу классификации. В чем отличие RecSys от классификации?

 - Много предсказаний для 1 user (extreme classification)
 - Гораздо больший объем данных: 100K users, 10K items --> 1B предсказаний
 - Большинство товаров user никогда не видел --> Не взаимодействовал --> 0 не значит "не понравился"
 - Нет явного таргета. Не понятно, что значит "(не) понравился"
 - Feedback loop
 - Иногда важен порядок рекомендаций

In [78]:
pd.DataFrame([['Иван', 'Хлеб Бородинский', 1],
              ['Иван', 'Хлеб Белый', 0],
              ['Иван', 'Йогурт Epica', "?"],
              ['Василий', 'Хлеб Бородинский', "?"],
              ['Василий', 'Хлеб Белый', "?"],
              ['Василий', 'Йогурт Epica', 1]], columns=['user', 'item', 'purchase_fact'])

      user              item purchase_fact
0     Иван  Хлеб Бородинский             1
1     Иван        Хлеб Белый             0
2     Иван      Йогурт Epica             ?
3  Василий  Хлеб Бородинский             ?
4  Василий        Хлеб Белый             ?
5  Василий      Йогурт Epica             1

----

## Основные типы задач:
    
**Рекомендация топ-К товаров**: Дан список товаров. Рекомендовать пользователю K товаров, которые ему понравятся
    - e-mail рассылки (М.Видео, Hoff, Пятерочка)
    - push-уведомления (Delivery Club, HeadHunter, Виктория)
    - Рекомендации в отдельном окне на сайте (vk, okko)

**Ранжирование товаров**: Дан список товаров. Нужно его отранжировать в порядке убывания интереса для пользователя
    - Ранжирование каталога товаров (Wildberries, Lamoda)
    - Ранжирование ленты (vk, Я.Дзен)
    - Ранжирование поисковой выдачи (Яндекс, Гугл)
    - Ранжирование "каруселей" товаров (Delivery Club, Я.Еда)
    
**Поиск похожих товаров**: Дан 1 товар. Нужно найти наиболее похожие на него товары
    - "Вам также может понравиться" (Ozon, Циан)
    - Похожим пользователям понравилось (vk)
    - Вы можете быть знакомы (vk, facebook)
    
**Рекомендация дополнителдьного товара**. Дан 1 товар. Найти товары, которые покупают вместе с этим товаром
    - С этим товаром часто покупают (Я.Маркет, Ozon, М.Видео)

---

# 2. ML-mетрики качества

*Хороши ли рекомендации, предлагаемые моделью?*  
Обычно считаются для каждого юзера, затем усредняются по юзерам

Представим, что рекомендовано всего 10 товаров
Куплено - 4 товара, некоторые не из рекомендованного списка

In [79]:
recommended_list = [27, 156, 1134, 991, 27, 1543, 3345, 533, 11, 43] #id товаров
bought_list = [521, 32, 143, 3345]

In [80]:
len(recommended_list)

10

### 1. Hit rate

Hit rate = был ли хотя бы 1 релевантный товар среди рекомендованных

- Иногда применяется, когда продаются достаточно дрогие товары (например, бытовая техника)

----
Hit rate = (был ли хотя бы 1 релевантный товар среди рекомендованных)   

Hit rate@k = (был ли хотя бы 1 релевантный товар среди топ-k рекомендованных)

In [81]:
def hit_rate(recommended_list, bought_list):

    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)

    flags = np.isin(bought_list, recommended_list)

    hit_rate = (flags.sum() > 0) * 1

    return hit_rate


def hit_rate_at_k(recommended_list, bought_list, k=5):

    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list[:k])

    flags = np.isin(bought_list, recommended_list)

    hit_rate = (flags.sum() > 0) * 1

    return hit_rate

In [82]:
hit_rate(recommended_list, bought_list)

np.int64(1)

In [83]:
hit_rate_at_k(recommended_list, bought_list)

np.int64(0)

### 2. Precision

*Precision* - доля релевантных товаров среди рекомендованных = Какой % рекомендованных товаров  юзер купил

- Пожалуй, самая приближенная к бизнес-метрикам и самая популярная метрика

---

Precision= (# of recommended items that are relevant) / (# of recommended items)  

Precision@k = (# of recommended items @k that are relevant) / (# of recommended items @k)

Money Precision@k = (revenue of recommended items @k that are relevant) / (revenue of recommended items @k)  

**Note:** Обычно k в precision@k достаточно невелико (5-20) и определяется из бизнес-логики. Например, 5 товаров в e-mail рассылке, 20 ответов на первой странице google и т.д

Красная рыба - 400 руб  
Молоко - 60 руб  
Хлеб = 40 руб  
Гречка = 40 руб  
Шоколад = 90 руб  

------  
Варенье - 240 руб  
...  

**Case 1**
рекомендовали - Красная рыба, Молоко, Хлеб, Гречка, Шоколад
купили из рекомендованного 1 и последний товар


prices_reсommended = [400, 60, 40, 40 , 90]  
flags = [1, 0, 0, 0 , 1]  

$precison@5 = \frac{1 + 0 + 0 +0 + 1}{1+1+1+1+1} = 40\%$  
$money precision@5 = \frac{1*400 + 0*60 + ... + 1*90}{1*400 + 1*60 + ... + 1*90} = 77.7\%$  

  
**Case 2**   
рекомендовали - Молоко, Красная рыба,  Хлеб, Гречка, Шоколад
купили из рекомендованного 1 и последний товар


prices_reсommended = [60, 400,  40, 40 , 90]  
flags = [1, 0,  0, 0 , 1]  

$precison@5 = \frac{0 + 1 + 0 +0 + 1}{1+1+1+1+1} = 40\%$  
$money precision@5 = \frac{0*400 + 1*60 + ... + 1*90}{1*400 + 1*60 + ... + 1*90} = 15.8\%$

In [84]:
def precision(recommended_list, bought_list):

    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)

    flags = np.isin(recommended_list, bought_list)

    precision = flags.sum() / len(recommended_list)

    return precision


def precision_at_k(recommended_list, bought_list, k=5):
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]

    flags = np.isin(recommended_list, bought_list)

    precision = flags.sum() / len(recommended_list)

    return precision


def money_precision_at_k(recommended_list, bought_list, prices_recommended, k=5):

    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]
    prices_recommended = np.array(prices_recommended)[:k]

    flags = np.isin(recommended_list, bought_list)

    precision = np.dot(flags, prices_recommended) / prices_recommended.sum()

    return precision

In [85]:
recommended_list = [27, 3345, 143, 991, 27, 1543, 533, 11, 43, 1234] #id товаров
prices_reсommended = [100, 80, 50, 30, 1000, 1000, 50, 1000, 1000, 50]

bought_list = [521, 32, 143, 3345]

In [86]:
precision(recommended_list, bought_list)

np.float64(0.2)

In [87]:
precision_at_k(recommended_list, bought_list, k=5)

np.float64(0.4)

In [88]:
precision_at_k(recommended_list, bought_list, k=3)

np.float64(0.6666666666666666)

In [89]:
money_precision_at_k(recommended_list, bought_list, prices_reсommended, k=3)

np.float64(0.5652173913043478)

### 3. Recall

*Recall* - доля рекомендованных товаров среди релевантных = Какой % купленных товаров был среди рекомендованных

- Обычно используется для моделей пре-фильтрации товаров (убрать те товары, которые точно не будем рекомендовать)

---

Recall= (# of recommended items that are relevant) / (# of relevant items)  

Recall@k = (# of recommended items @k that are relevant) / (# of relevant items)

Money Recall@k = (revenue of recommended items @k that are relevant) / (revenue of relevant items)  

    
  
**Note:** в recall@k число k обычно достаточно большое (50-200), больше чем покупок у среднестатистического юзера

In [90]:
def recall(recommended_list, bought_list):

    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)

    flags = np.isin(bought_list, recommended_list)

    recall = flags.sum() / len(bought_list)

    return recall


def recall_at_k(recommended_list, bought_list, k=5):

    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]

    flags = np.isin(bought_list, recommended_list)

    recall = flags.sum() / len(bought_list)

    return recall


def money_recall_at_k(recommended_list, bought_list, prices_bought, k=5):

    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]
    prices_bought = np.array(prices_bought)

    flags = np.isin(bought_list, recommended_list)

    recall = np.dot(flags, prices_bought) / prices_bought.sum()

    return recall

In [91]:
recommended_list = [27, 3345, 143, 991, 27, 1543, 533, 11, 43, 1234] #id товаров
prices_reсommended = [100, 80, 50, 30, 1000, 1000, 50, 1000, 1000, 50]

bought_list = [521, 32, 143, 3345]
prices_bought = [20, 100, 25, 120]

In [92]:
recall(recommended_list, bought_list)

np.float64(0.5)

In [93]:
recall_at_k(recommended_list, bought_list, k=5)

np.float64(0.5)

In [94]:
money_recall_at_k(recommended_list, bought_list, prices_bought, k=5)

np.float64(0.5471698113207547)

---

# Метрики ранжирования

Если важен порядок рекомендаций. Подробнее можно почитать [здесь](https://habr.com/ru/company/econtenta/blog/303458/). Формулы в статье могут несколько отличаться от формул в лекции

## AP@k
AP@k - average precision at k

$$AP@k = \frac{1}{r} \sum{[recommended_{relevant_i}] * precision@k}$$

- r - кол-во релевантный среди рекомендованных
- Суммируем по всем релевантным товарам
- Зависит от порядка реокмендаций

In [95]:
def ap_k(recommended_list, bought_list, k=5):

    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)

    flags = np.isin(recommended_list, bought_list)

    if sum(flags) == 0:
        return 0

    sum_ = 0
    for i in range(0, k):
        if flags[i] == True:
            p_k = precision_at_k(recommended_list, bought_list, k=i+1)
            sum_ += p_k

    result = sum_ / sum(flags)

    return result

In [96]:
ap_k(recommended_list, bought_list, k=5)

np.float64(0.5833333333333333)

### MAP@k

MAP@k (Mean Average Precision@k)  
Среднее AP@k по всем юзерам
- Показывает средневзвешенную точность рекомендаций

$$MAP@k = \frac{1}{|U|} \sum_u{AP_k}$$
  
|U| - кол-во юзеров

In [97]:
recommended_list = [[143, 156, 1134, 991, 27, 1543, 3345, 533, 11, 43],
                    [146, 156, 1134, 991, 27, 1543, 3345, 533, 11, 43],] #id товаров
bought_list = [[521, 32, 143, 991], [146, 29]]

In [98]:
def map_k(recommended_list, bought_list, k=5, u=1):

    recommended_list = recommended_list[:u]
    bought_list = bought_list[:u]
    sum_ap_k = 0

    for i in range(len(bought_list)):
        ap_k_result = ap_k(recommended_list[i], bought_list[i], k)
        sum_ap_k += ap_k_result

    result = sum_ap_k / len(bought_list)

    return result

In [99]:
map_k(recommended_list, bought_list, k=5, u=2)

np.float64(0.875)

### AUC@k
AUC для первых k наблюдений  
- Можно посчитать как sklern.metrics.roc_auc_score для топ-k предсказаний
- Показывает долю верно отранжированных товаров

### NDCG@k
Normalized discounted cumulative gain

$DCG = \frac{1}{|r|} \sum_u{\frac{[bought fact]}{discount(i)}}$  

$discount(i) = 1$ if $i <= 2$,   
$discount(i) = log_2(i)$ if $i > 2$


(!) Считаем для первых k рекоммендаций   
(!) - существуют вариации с другими $discount(i)$  
i - ранк рекомендованного товара  
|r| - кол-во рекомендованных товаров

$$NDCG = \frac{DCG}{ideal DCG}$$

https://pytorch.org/docs/stable/index.html

In [100]:
import torch
N = 5
ys_true = torch.randint(0, 5, (N, ))
ys_pred = torch.rand(N)

In [101]:
ys_true

tensor([3, 2, 3, 1, 3])

In [102]:
ys_pred

tensor([0.9013, 0.2808, 0.9448, 0.0213, 0.0626])

In [103]:
# итоговый результат модели - отсортированный ys_pred
ys_pred

tensor([0.9013, 0.2808, 0.9448, 0.0213, 0.0626])

In [104]:
ys_pred

tensor([0.9013, 0.2808, 0.9448, 0.0213, 0.0626])

In [105]:
def compute_gain(y_value: float, gain_scheme: str) -> float:
    if gain_scheme == "exp2":
        gain = 2 ** y_value - 1
    elif gain_scheme == "const":
        gain = y_value
    else:
        raise ValueError(f"{gain_scheme} method not supported, only exp2 and const.")
    return float(gain)

In [106]:
def dcg(ys_true: torch.Tensor, ys_pred: torch.Tensor, gain_scheme: str) -> float:
    _, argsort = torch.sort(ys_pred, descending=True, dim=0)
    ys_true_sorted = ys_true[argsort]
    ret = 0
    for idx, cur_y in enumerate(ys_true_sorted, 1):
        gain = compute_gain(cur_y, gain_scheme)
        ret += gain / torch.log2(torch.tensor(idx + 1, dtype=torch.float))
    return ret

In [107]:
_, argsort = torch.sort(ys_pred, descending=True, dim=0)

In [108]:
ys_pred

tensor([0.9013, 0.2808, 0.9448, 0.0213, 0.0626])

In [109]:
argsort

tensor([2, 0, 1, 4, 3])

In [110]:
ys_true_sorted = ys_true[argsort]

In [111]:
for idx, cur_y in enumerate(ys_true_sorted, 1):
    print(idx, cur_y)

1 tensor(3)
2 tensor(3)
3 tensor(2)
4 tensor(3)
5 tensor(1)

In [112]:
print(ys_true_sorted)
print(ys_true_sorted.sum())

tensor([3, 3, 2, 3, 1])
tensor(12)

In [113]:
def ndcg(ys_true: torch.Tensor, ys_pred: torch.Tensor, gain_scheme: str = 'const') -> float:
    pred_dcg = dcg(ys_true, ys_pred, gain_scheme)

    ideal_dcg = dcg(ys_true, ys_true, gain_scheme)

    ndcg = pred_dcg / ideal_dcg
    return ndcg

In [114]:
ndcg(ys_true, ys_pred)

tensor(0.9909)

### MRR@k
Mean Reciprocal Rank

- Считаем для первых k рекоммендаций
- Найти ранк первого релевантного предсказания $k_u$
- Посчитать reciprocal rank = $\frac{1}{k_u}$

$$MRR = mean(\frac{1}{k_u})$$

[MRR](https://drive.google.com/file/d/1uMFKqWULFmehS0pJtvXKRygjYxQOPise/view?usp=sharing)

In [115]:
def reciprocal_rank(recommended_list, bought_list):
    for i, item in enumerate(recommended_list, 1):
        if item in bought_list:
            return 1.0 / i
    return 0.0

In [116]:
print(reciprocal_rank([10, 20, 30, 40], [10, 50]))

1.0

In [117]:
print(reciprocal_rank([10, 20, 30, 40], [30, 40]))

0.3333333333333333

# 3. Связь бизнес-метрик, ML-метрик и функции потерь(loss)

- **loss** - то, что оптимизирует модель (RMSE - Root Mean Squared Error)
- **ML-метрика** - то, как мы измеряем качество на test (money precision@5)
- **Бизнес-метрика** - то, что хочет оптимизировать бизнес (выручка)

В идеале loss = ML-метрика = бизнес-метрика, но это возмонжо в очень редких случаях

Надеемся, что:  
    *Оптимизация loss --> рост ML-метрик --> рост бизнес-метрик*

### Пример: рекомендательная система товаров на сайте  
      
На сайте есть баннер, на котором мы можем разместить 5 товаров. Надо порекомендовать эти 5 товаров персонально каждому юзеру

*Шаг 1: Определим бизнес-метрику*  
Бизнес хочет максимизировать выручку --> бизнес-метрика - **Выручка**  

*Шаг 2: Разложим ее на составляющие*  
Выручка =   
       Средний чек * кол-во покупок =   
       Средний чек * (число юзеров * конверсия из захода на сайт в заказ) =
       Число юзеров * (Средний чек * конверсия из захода на сайт в заказ)
       
Рекомендательная система влияет только на (Средний чек * конверсия из захода на сайт в заказ).   
Хорошим приближением этого является **money precision@5** - ML-метрика

*Шаг 3: loss*  
Это существенно сложнее. Персонализированные ML-модели не умеют напрямую оптимизировать конверсию. Стандартный loss - **RMSE**. Можно для начала попробовать его.

P.S. Если вы хотите приблизить RMSE к money precision@5, то можно посчитать weighted RMSE, где вес каждого наблюдения = стоимость товара.   
P.S.S. Про другие виды loss будет рассказано в курсе